sudo: false
language: python
matrix:
  allow_failures:
    - os: osx
    - env: DJANGO_VERSION=3.0.2
os:
  - linux
  - osx
env:
  - DJANGO_VERSION=2.2.9
  - DJANGO_VERSION=3.0.2
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install:
  - pip install virtualenv
  - pip install codecov
install:
  - python setup.py install
script:
  - coverage run manage.py jenkins --enable-coverage -v 2
after_success:
  - codecov
