language: python
jobs:
  allow_failures:
    - os: osx
    - env: DJANGO_VERSION=4
  include:
    - os: linux
    - os: osx
env:
  - DJANGO_VERSION=3
  - DJANGO_VERSION=4
python:
  - '3.7'
  - '3.8'
  - '3.9'
before_install:
  - python -m pip install --upgrade pip
  - pip install virtualenv
  - pip install .[testing,linting]
  - pip install "Django<$DJANGO_VERSION"
install:
  - python setup.py install
script:
  - coverage run manage.py test --exe --all-modules
after_success:
  - codecov